apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v4
  namespace: hands-on
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: v4
  template:
    metadata:
      labels:
        app: demo
        version: v4
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: highcpu-pool
      containers:
        - name: web
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "700m"
              memory: "128Mi"
            limits:
              cpu: "1200m"
              memory: "256Mi"

